configData:
  version: 0.1
  log:
    fields:
      service: registry
  storage:
    cache:
      blobdescriptor: inmemory
  http:
    addr: :5000
    headers:
      X-Content-Type-Options: [nosniff]
    debug:
      addr: :5001
      prometheus:
        enabled: false
        path: /metrics
  health:
    storagedriver:
      enabled: true
      interval: 10s
      threshold: 3
  secrets:
    htpasswd: "user:$2y$05$zDST8320bM1EcRhcj2nsheN7conl3kkOWxPXESn.HW/1lnThDmoBG"
