{
 "title": "Version Checker - Internals",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Version Checker Namespace",
    "query": {
     "query": "label_values(version_checker_is_latest_version,namespace)"
    }
   },
   {
    "name": "domains",
    "label": "Domains",
    "query": {
     "query": "label_values(http_client_requests_total{namespace=\"$namespace\"},domain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Controller Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "95th Percentile Reconciliation Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    histogram_quantile(0.95, rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"pod\", namespace=\"$namespace\"}[5m]))\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Workqueue Depth (Pending Items)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(workqueue_depth{controller=\"pod\",namespace=\"$namespace\"}) by (controller)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average Reconciliation Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_time_seconds_sum{namespace=\"$namespace\"}[5m]) / \nrate(controller_runtime_reconcile_time_seconds_count{namespace=\"$namespace\"}[5m])) by (controller)\n",
     "legendFormat": "{{controller}} {{result}}"
    }
   ]
  },
  {
   "title": "Queue Processing Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{controller=\"pod\",namespace=\"$namespace\"}[5m])) by (controller)\n",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{namespace=\"$namespace\"}[$__rate_interval])) by (controller)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of reconciliations per controller.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{controller=\"pod\", namespace=\"$namespace\"}[5m])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Reconcile Errors ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "increase(controller_runtime_reconcile_errors_total{controller=\"pod\",namespace=\"$namespace\"}[5m])\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "HTTP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "HTTP Successful Requests",
   "type": "timeseries",
   "description": "HTTP Requests by Domain along with inflight HTTP Requests",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_in_flight_requests{namespace=~\"$namespace\", domain=~\"$domains\", code=\"OK\"}[1m]))",
     "legendFormat": "Inflight"
    },
    {
     "expr": "avg(rate(http_client_requests_total{namespace=\"$namespace\", domain=~\"$domains\", code=\"OK\"}[1m])) by (domain)",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "HTTP Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(http_client_in_flight_requests{namespace=~\"$namespace\"})",
     "legendFormat": "Inflight"
    },
    {
     "expr": "sum(increase(http_client_requests_total{namespace=\"$namespace\", domain=~\"$domains\", code!=\"OK\"}[10m])) by (domain,code)",
     "legendFormat": "{{domain}} / {{code}}"
    }
   ]
  },
  {
   "title": "DNS / TLS Resolution",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n    rate(http_dns_duration_seconds{event=\"dns_done\",namespace=~\"$namespace\",domain=~\"$domains\"}[1m])\n) by (domain)",
     "legendFormat": "DNS: {{domain}}"
    },
    {
     "expr": "avg(\n    rate(http_tls_duration_seconds{event=\"tls_done\", namespace=~\"$namespace\"}[1m])\n)by (domain)",
     "legendFormat": "TLS: {{domain}}"
    }
   ]
  },
  { "title": "Core Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Process CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=\"version-checker\"}[1m])",
     "legendFormat": "CPU Seconds: {{pod}}"
    },
    {
     "expr": "max(rate(process_cpu_seconds_total{namespace=\"version-checker\"}[1h])) by (pod)",
     "legendFormat": "Max Hour: {{pod}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"version-checker\"}",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  { "title": "Go Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Go GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{namespace=\"$namespace\"}[5m])",
     "legendFormat": "GC Duration"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\"}",
     "legendFormat": "Go Routines"
    },
    {
     "expr": "go_threads{namespace=\"$namespace\"}",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Go Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{namespace=\"$namespace\", container=\"version-checker\"}",
     "legendFormat": "Allocated Bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{namespace=\"$namespace\", container=\"version-checker\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "go_memstats_heap_objects{namespace=\"$namespace\", container=\"version-checker\"}",
     "legendFormat": "Objects"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{namespace=\"$namespace\"}",
     "legendFormat": "System"
    }
   ]
  },
  { "title": "Container Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Container Uptime",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{namespace=\"$namespace\",container!=\"POD\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replica Counts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=~\"$namespace\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"}",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod, container)(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container=\"version-checker\"}[5m]))\n",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod, container)(container_memory_usage_bytes{container=\"version-checker\",namespace=~\"$namespace\"})",
     "legendFormat": "Usage: {{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Container Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",container=\"POD\"}[5m]))",
     "legendFormat": "Transmit: {{pod}}"
    },
    {
     "expr": "sum by (pod)(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",container=\"POD\"}[5m]))",
     "legendFormat": "Received: {{pod}}"
    }
   ]
  }
 ]
}