apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    etcd:
      local:
        extraArgs:
          unsafe-no-fsync: "true"
    networking:
      serviceSubnet: 10.0.0.0/16
nodes:
- role: control-plane

  extraPortMappings:
  - containerPort: 30443
    hostPort: 30443
    listenAddress: "0.0.0.0"
    protocol: tcp

  extraMounts:
  - hostPath: {{KIND_IMAGES}}
    containerPath: /mounted_images

containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker-registry.registry.svc.cluster.local:5000"]
    endpoint = ["http://localhost:30443"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."docker-registry.registry.svc.cluster.local:5000".tls]
    insecure_skip_verify = true
