{{- if or  .Values.prometheus.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prometheus.serviceAccountName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus
subjects:
- kind: ServiceAccount
  name: {{ .Values.prometheus.serviceAccountName }}
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ include "version-checker.name" . }}
  labels:
    prometheus: {{ include "version-checker.name" . }}
{{ include "version-checker.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.prometheus.replicas }}
  serviceAccountName: {{ .Values.prometheus.serviceAccountName }}
  version: v2.20.1
  serviceMonitorSelector:
    matchLabels:
      app: {{ include "version-checker.name" . }}
{{- end }}
