apiVersion: v1
kind: Service
metadata:
  name: {{ include "version-checker.name" . }}
  labels:
    app: {{ include "version-checker.name" . }}
    {{ include "version-checker.labels" . | nindent 4 }}
    {{- if .Values.svc.annotations }}
    {{ toYaml .Values.pod.annotations | nindent 4 }}
    {{- end }}
  {{- if .Values.svc.annotations }}
  annotations:
    {{ toYaml .Values.pod.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: web
  selector:
    {{ include "version-checker.labels" . | nindent 4 }}
