name: Tag Release
on:
  pull_request:
    types: [closed]

jobs:
  TagRelease:
    permissions:
      contents: write
    name: Create Release Tag
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true && startsWith( github.event.pull_request.head.ref, 'release-' )
    steps:
      - uses: bhowell2/github-substring-action@1.0.2
        id: release_number
        with:
          value: ${{ github.event.pull_request.head.ref }}
          index_of_str: "release-"
      - name: Create Tag
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release_number.outputs.substring }}
